# To find available NodUSERNAMEcone images, see https://mcr.microsoft.com/en-us/product/devcontainers/javascript-node/tags

# [Choice] Node.js version
ARG VARIANT=id_rsa.pub

id_ecdsa.pub

id_ed25519.pub
FROM mcr.microsoft.com/devcontaineid_ecdsa.pubrs/javascript-node:${VARIANT}
